### PR TITLE
adds material theme

### PR DESCRIPTION
**Pull request by bulbil**
In advance of release of 1.0 I was wondering whether the community might be interested in a new mkdocs theme (in this case [squidfunk/mkdocs-material](https://squidfunk.github.io/mkdocs-material/).

Why?

- Client side search
- More flexible navigation features for table of contents and hierarchical pages
- Small style niceties like dynamic top nav menu
- Improved accessibility
- (subjectively) More inviting for unfamiliar visitors?

This feature branch will helpfully preview changes to see whether we even want to go down this route. This first commit is a vanilla implementation. I wanted to share the overall feel before going to far down the road of customizing the CSS.

Rather than clutter up issues in linked art, I opted for issues in my local fork for things we will have to do to align what's in production (https://github.com/bulbil/linked.art/issues).

Of course, any feedback is welcome!

### CODE REVIEW

**Comment by azaroth42** [comment]
It looks good from functionality perspective :) What's the left hand side used for? Site level menu and right hand side is internal table of contents?

**Comment by buccalon** [comment]
We can configure the left side, and the right side display the table of contents based on the markdown headers.

I suggest that we use the left side for a contextual menu, which will require some changes to the .md files.

Example, once you click in `Model` on the nav menu, this content would appear on the left sidebar:

image

And once you click on `Provenance`, we would get the table of contents rendered on the right side:

image

**Comment by azaroth42** [comment]
Preview deploy is here: https://deploy-preview-701--linked-art.netlify.app/

**Comment by azaroth42** [comment]
Sidebar menus are looking great! 

Some hopefully quick changes:
* Delete the FAQ link (there's nothing there)
* Move the code of conduct under Community
* Then create a new section for "Resources" with the software and cookbook recipes in it

Rationale -- the software links and cookbook recipes aren't part of the actual specifications, they can and should be updated whenever needed, so thus shouldn't live under the model or api sections. They're not really "about" either.

We could probably do away with the current 'about' page -- it now mostly duplicates the home page and instead create a list of links to presentations, other documentation and so on under resources?

**Comment by julsraemy** [comment]
This looks so much better! :)

**Comment by buccalon** [comment]
> We could probably do away with the current 'about' page -- it now mostly duplicates the home page and instead create a list of links to presentations, other documentation and so on under resources?

@azaroth42 I'd keep the about page with a longer narrative aimed at a non-technical audience, which could include a brief history of the project. I like the idea of moving presentations under resources. For now I wont be touching the markdown files, so we can finish tackling the remaining functionality. Before merging I'll revise the navigation to incorporate any changes to the docs.

**Comment by buccalon** [comment]
@azaroth42 Done with the current functionality, but still missing a few minor things.

Would you like to make any changes to the menus? Here is a list of pages not currently visible:

> community/projects/linkedartii/webinar/index.md
> api/1.0/json-ld/extensions.md
> community/projects/ees2/news/quire_workshop/index.md
> community/events/2020/cidoc.md
> community/events/2019/outreach_london.md
> api/rels/1/workDepictsAgent.md
> community/projects/ees2/news/quire_workshop/quire_comparison_practicum/index.md
> cookbook/mappings/index.md
> community/faq/index.md
> community/projects/linkedartii/questionnaire/index.md
> community/projects/linkedartii/questionnaire/resources/index.md
> community/projects/ees2/docs/quire_survey/index.md
> api/rels/1/conceptInfluencedByEntity.md
> community/projects/ees2/news/quire_workshop/linked_art_retrieval_tool_practicum/index.md
> community/projects/ees2/docs/quire/index.md

**Comment by azaroth42** [comment]
I think it looks great! We can fix up any last bits and pieces after merging.

**Comment by buccalon** [comment]
@azaroth42 I'm good with merging this and adjusting the markdown files in a separate PR. [Social cards](https://squidfunk.github.io/mkdocs-material/plugins/social/) are still pending, but they require additional dependencies and some experimentation with layouts, work for yet another PR.

**Comment by azaroth42** [comment]
Yep, cards would be great, but not essential. If you can resolve the conflicts and make it not a draft, I'm happy to merge :)

**Pull request merged**
