### PR TITLE
Improve website design

### PR DESCRIPTION
**Pull request by buccalon**
image

---

Preview: https://deploy-preview-674--linked-art.netlify.app/

---

This PR partially addresses issues #612 and #629:

- [X] Add horizontal version of the Linked Art logo
- [X] Add font `IBM Plex Mono` for section headers
- [X] Fixes Google Slides embed on homepage
- [X] Improve layout spacing and html/css tags
- [X] Hide/show top menu on scroll

### CODE REVIEW

**Comment by azaroth42** [comment]
Can you put back the current logo for now? Getting the look and feel improved is much more important than changing the logo out (which I think would need a good amount of discussion)

**Comment by buccalon** [comment]
Sure, I'll concentrate this PR on #612 and #629, and add my comments on the logo to #538

**Comment by azaroth42** [comment]
Nice! I like the hiding/showing menu on scrolling idea :) And the horizontal layout of the logo is great too!

**Comment by azaroth42** [comment]
Is it still in progress or shall we merge?

**Comment by julsraemy** [comment]
Looks really nice!

**Comment by buccalon** [comment]
> Is it still in progress or shall we merge?

This one is good to go, just wanted your feedback first.

There are minor things I'd like to keep working on, but that can become a separate PR.

**Comment by azaroth42** [comment]
Many thanks!

**Pull request merged**
